# Generated by Django 4.1.7 on 2023-02-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeer',
            new_name='joel',
        ),
    ]
