# Generated by Django 4.1.7 on 2023-02-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0002_rename_employeer_joel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joel',
            name='emp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
