# Generated by Django 4.1.7 on 2023-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0003_alter_employee_emp_id_alter_joel_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joel',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
