# Generated by Django 4.1.7 on 2023-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0004_alter_employee_emp_id_alter_joel_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
