# Generated by Django 4.1.7 on 2023-02-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0006_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='joel',
            name='iid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
