# Generated by Django 4.1.4 on 2023-02-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0008_alter_employee_aadhar_alter_joel_aadhar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='superadmin',
        ),
    ]
