# Generated by Django 4.1.7 on 2023-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0009_delete_superadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='joel',
            new_name='employeer',
        ),
    ]
