# Generated by Django 4.1.4 on 2023-02-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0010_rename_joel_employeer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='aadhar',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='employeer',
            old_name='aadhar',
            new_name='password',
        ),
    ]
