# Generated by Django 4.1.4 on 2023-02-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0011_rename_aadhar_employee_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='employeer',
            old_name='password',
            new_name='aadhar',
        ),
    ]
