# Generated by Django 4.1.4 on 2023-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0013_employee_registration_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_registration_database',
            name='Aadhar_ID_Number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_registration_database',
            name='Email_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_registration_database',
            name='Mobile_Number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeer_access_database',
            name='Aadhar_ID_Number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeer_access_database',
            name='Email_ID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeer_access_database',
            name='Mobile_Number',
            field=models.CharField(max_length=100),
        ),
    ]
