# Generated by Django 4.1.7 on 2023-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0014_alter_employee_registration_database_aadhar_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_registration_database',
            name='Employee_ID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_registration_database',
            name='Increment_ID',
            field=models.IntegerField(null=True),
        ),
    ]
