# Generated by Django 4.1.4 on 2023-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0016_employer_access_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eployers_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incrementing_ID', models.IntegerField(null=True)),
                ('Employers_ID', models.CharField(max_length=100, null=True)),
                ('Employer_Name', models.CharField(max_length=100)),
                ('Email_ID', models.CharField(max_length=100)),
                ('Employer_Number', models.CharField(max_length=100)),
                ('Employer_Company_Name', models.CharField(max_length=100)),
                ('Registered_Date', models.DateField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee_registration_database',
            name='Community',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_registration_database',
            name='Section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer_access_database',
            name='Community',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer_access_database',
            name='Section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
