# Generated by Django 4.1.4 on 2023-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0018_employers_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers_selection',
            name='Registered_Date',
        ),
        migrations.AddField(
            model_name='employers_selection',
            name='Email_ID1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employers_selection',
            name='Registered_Date1',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
